'use client';

import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { Sparkles, ShieldCheck } from 'lucide-react';
import { EndpointTestSuite } from '@/lib/types';

interface AiTestBadgeProps {
  testSuite?: EndpointTestSuite;
  nodeName: string;
}

export const AiTestBadge: React.FC<AiTestBadgeProps> = ({ testSuite, nodeName }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!testSuite) return null;

  const count = testSuite.testCases.length;
  const isGemini = testSuite.generatedBy === 'gemini_ai';

  const modalContent = (
    <div 
      onClick={(e) => e.stopPropagation()}
      className="fixed inset-0 z-[9999] flex items-center justify-center bg-slate-950/85 p-4 backdrop-blur-md animate-in fade-in duration-150"
    >
      <div className="w-full max-w-lg rounded-2xl border border-slate-800 bg-slate-900 p-5 shadow-2xl my-auto">
        <div className="flex items-center justify-between pb-3 border-b border-slate-800">
          <div className="flex items-center space-x-2">
            <ShieldCheck className="h-5 w-5 text-indigo-400" />
            <div>
              <h3 className="text-sm font-semibold text-white">{nodeName}</h3>
              <span className="text-[11px] text-purple-400 flex items-center gap-1">
                <Sparkles className="h-3 w-3" />
                {isGemini ? 'Generated by AI Test Engine' : 'Smart Baseline Heuristic Engine'}
              </span>
            </div>
          </div>
          <button
            onClick={() => setIsOpen(false)}
            className="text-slate-400 hover:text-slate-200"
          >
            ✕
          </button>
        </div>

        <p className="mt-3 text-xs text-slate-400 italic">
          "{testSuite.summary}"
        </p>

        <div className="mt-4 space-y-2 max-h-72 overflow-y-auto pr-1 custom-scrollbar">
          {testSuite.testCases.map((tc, idx) => (
            <div
              key={tc.id || idx}
              className="rounded-xl border border-slate-800/80 bg-slate-950/60 p-3 text-xs flex flex-col space-y-1"
            >
              <div className="flex items-center justify-between font-medium text-slate-200">
                <span className="flex items-center gap-1.5">
                  <span className="flex h-5 w-5 items-center justify-center rounded-md bg-indigo-500/10 text-[10px] font-bold text-indigo-400">
                    #{idx + 1}
                  </span>
                  {tc.description}
                </span>
                <span className="uppercase tracking-wider text-[9px] font-bold text-indigo-400 bg-indigo-950/80 px-2 py-0.5 rounded border border-indigo-800/50">
                  {tc.type.replace('_', ' ')}
                </span>
              </div>

              {tc.expectedValue !== undefined && (
                <div className="text-[11px] text-slate-400 flex items-center gap-1 pl-6">
                  <span className="text-slate-500">Expected:</span>
                  <code className="text-emerald-400 font-mono bg-slate-900 px-1.5 py-0.5 rounded border border-slate-800">
                    {String(tc.expectedValue)}
                  </code>
                </div>
              )}

              {tc.jsonPath && (
                <div className="text-[11px] text-slate-400 flex items-center gap-1 pl-6">
                  <span className="text-slate-500">JSON Path:</span>
                  <code className="text-amber-400 font-mono bg-slate-900 px-1.5 py-0.5 rounded border border-slate-800">
                    {tc.jsonPath}
                  </code>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="mt-5 flex justify-end">
          <button
            onClick={() => setIsOpen(false)}
            className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-semibold text-white hover:bg-indigo-500"
          >
            Close Inspector
          </button>
        </div>
      </div>
    </div>
  );

  return (
    <>
      <button
        onClick={(e) => {
          e.stopPropagation();
          setIsOpen(true);
        }}
        className={`inline-flex items-center space-x-1 rounded-full px-2 py-0.5 text-[10px] font-medium transition-all ${
          isGemini
            ? 'bg-gradient-to-r from-purple-900/60 to-indigo-900/60 text-purple-200 border border-purple-500/30 hover:border-purple-400'
            : 'bg-slate-800 text-slate-300 border border-slate-700 hover:bg-slate-700'
        }`}
        title="Click to view AI Generated Test Rules"
      >
        <Sparkles className="h-3 w-3 text-purple-400" />
        <span>{count} AI Tests</span>
      </button>

      {isOpen && mounted && createPortal(modalContent, document.body)}
    </>
  );
};
