export interface CountryData {
  code: string;
  name: string;
  flag: string;
  iso: string;
}

export const ALL_WORLD_COUNTRIES: CountryData[] = [
  { code: '+46', name: 'Sweden', flag: '🇸🇪', iso: 'SE' },
  { code: '+91', name: 'India', flag: '🇮🇳', iso: 'IN' },
  { code: '+1', name: 'United States', flag: '🇺🇸', iso: 'US' },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧', iso: 'GB' },
  { code: '+358', name: 'Finland', flag: '🇫🇮', iso: 'FI' },
  { code: '+47', name: 'Norway', flag: '🇳🇴', iso: 'NO' },
  { code: '+45', name: 'Denmark', flag: '🇩🇰', iso: 'DK' },
  { code: '+49', name: 'Germany', flag: '🇩🇪', iso: 'DE' },
  { code: '+33', name: 'France', flag: '🇫🇷', iso: 'FR' },
  { code: '+39', name: 'Italy', flag: '🇮🇹', iso: 'IT' },
  { code: '+34', name: 'Spain', flag: '🇪🇸', iso: 'ES' },
  { code: '+31', name: 'Netherlands', flag: '🇳🇱', iso: 'NL' },
  { code: '+41', name: 'Switzerland', flag: '🇨🇭', iso: 'CH' },
  { code: '+1', name: 'Canada', flag: '🇨🇦', iso: 'CA' },
  { code: '+61', name: 'Australia', flag: '🇦🇺', iso: 'AU' },
  { code: '+971', name: 'United Arab Emirates', flag: '🇦🇪', iso: 'AE' },
  { code: '+65', name: 'Singapore', flag: '🇸🇬', iso: 'SG' },
  { code: '+81', name: 'Japan', flag: '🇯🇵', iso: 'JP' },
  { code: '+55', name: 'Brazil', flag: '🇧🇷', iso: 'BR' },
  { code: '+48', name: 'Poland', flag: '🇵🇱', iso: 'PL' },
  { code: '+353', name: 'Ireland', flag: '🇮🇪', iso: 'IE' },
  { code: '+372', name: 'Estonia', flag: '🇪🇪', iso: 'EE' },
  { code: '+371', name: 'Latvia', flag: '🇱🇻', iso: 'LV' },
  { code: '+370', name: 'Lithuania', flag: '🇱🇹', iso: 'LT' },
  { code: '+43', name: 'Austria', flag: '🇦🇹', iso: 'AT' },
  { code: '+32', name: 'Belgium', flag: '🇧🇪', iso: 'BE' },
  { code: '+351', name: 'Portugal', flag: '🇵🇹', iso: 'PT' },
  { code: '+30', name: 'Greece', flag: '🇬🇷', iso: 'GR' },
  { code: '+420', name: 'Czech Republic', flag: '🇨🇿', iso: 'CZ' },
  { code: '+36', name: 'Hungary', flag: '🇭🇺', iso: 'HU' },
  { code: '+40', name: 'Romania', flag: '🇷🇴', iso: 'RO' },
  { code: '+380', name: 'Ukraine', flag: '🇺🇦', iso: 'UA' },
  { code: '+90', name: 'Turkey', flag: '🇹🇷', iso: 'TR' },
  { code: '+966', name: 'Saudi Arabia', flag: '🇸🇦', iso: 'SA' },
  { code: '+82', name: 'South Korea', flag: '🇰🇷', iso: 'KR' },
  { code: '+86', name: 'China', flag: '🇨🇳', iso: 'CN' },
  { code: '+60', name: 'Malaysia', flag: '🇲🇾', iso: 'MY' },
  { code: '+62', name: 'Indonesia', flag: '🇮🇩', iso: 'ID' },
  { code: '+64', name: 'New Zealand', flag: '🇳🇿', iso: 'NZ' },
  { code: '+52', name: 'Mexico', flag: '🇲🇽', iso: 'MX' },
  { code: '+54', name: 'Argentina', flag: '🇦🇷', iso: 'AR' },
  { code: '+27', name: 'South Africa', flag: '🇿🇦', iso: 'ZA' },
  { code: '+93', name: 'Afghanistan', flag: '🇦🇫', iso: 'AF' },
  { code: '+355', name: 'Albania', flag: '🇦🇱', iso: 'AL' },
  { code: '+213', name: 'Algeria', flag: '🇩🇿', iso: 'DZ' },
  { code: '+376', name: 'Andorra', flag: '🇦🇩', iso: 'AD' },
  { code: '+244', name: 'Angola', flag: '🇦🇴', iso: 'AO' },
  { code: '+374', name: 'Armenia', flag: '🇦🇲', iso: 'AM' },
  { code: '+994', name: 'Azerbaijan', flag: '🇦🇿', iso: 'AZ' },
  { code: '+973', name: 'Bahrain', flag: '🇧🇭', iso: 'BH' },
  { code: '+880', name: 'Bangladesh', flag: '🇧🇩', iso: 'BD' },
  { code: '+375', name: 'Belarus', flag: '🇧🇾', iso: 'BY' },
  { code: '+501', name: 'Belize', flag: '🇧🇿', iso: 'BZ' },
  { code: '+591', name: 'Bolivia', flag: '🇧🇴', iso: 'BO' },
  { code: '+387', name: 'Bosnia & Herzegovina', flag: '🇧🇦', iso: 'BA' },
  { code: '+359', name: 'Bulgaria', flag: '🇧🇬', iso: 'BG' },
  { code: '+56', name: 'Chile', flag: '🇨🇱', iso: 'CL' },
  { code: '+57', name: 'Colombia', flag: '🇨🇴', iso: 'CO' },
  { code: '+506', name: 'Costa Rica', flag: '🇨🇷', iso: 'CR' },
  { code: '+385', name: 'Croatia', flag: '🇭🇷', iso: 'HR' },
  { code: '+357', name: 'Cyprus', flag: '🇨🇾', iso: 'CY' },
  { code: '+593', name: 'Ecuador', flag: '🇪🇨', iso: 'EC' },
  { code: '+20', name: 'Egypt', flag: '🇪🇬', iso: 'EG' },
  { code: '+503', name: 'El Salvador', flag: '🇸🇻', iso: 'SV' },
  { code: '+995', name: 'Georgia', flag: '🇬🇪', iso: 'GE' },
  { code: '+502', name: 'Guatemala', flag: '🇬🇹', iso: 'GT' },
  { code: '+504', name: 'Honduras', flag: '🇭🇳', iso: 'HN' },
  { code: '+852', name: 'Hong Kong', flag: '🇭🇰', iso: 'HK' },
  { code: '+354', name: 'Iceland', flag: '🇮🇸', iso: 'IS' },
  { code: '+964', name: 'Iraq', flag: '🇮🇶', iso: 'IQ' },
  { code: '+972', name: 'Israel', flag: '🇮🇱', iso: 'IL' },
  { code: '+962', name: 'Jordan', flag: '🇯🇴', iso: 'JO' },
  { code: '+7', name: 'Kazakhstan', flag: '🇰🇿', iso: 'KZ' },
  { code: '+254', name: 'Kenya', flag: '🇰🇪', iso: 'KE' },
  { code: '+965', name: 'Kuwait', flag: '🇰🇼', iso: 'KW' },
  { code: '+961', name: 'Lebanon', flag: '🇱🇧', iso: 'LB' },
  { code: '+352', name: 'Luxembourg', flag: '🇱🇺', iso: 'LU' },
  { code: '+853', name: 'Macau', flag: '🇲🇴', iso: 'MO' },
  { code: '+389', name: 'North Macedonia', flag: '🇲🇰', iso: 'MK' },
  { code: '+356', name: 'Malta', flag: '🇲🇹', iso: 'MT' },
  { code: '+212', name: 'Morocco', flag: '🇲🇦', iso: 'MA' },
  { code: '+975', name: 'Bhutan', flag: '🇧🇹', iso: 'BT' },
  { code: '+977', name: 'Nepal', flag: '🇳🇵', iso: 'NP' },
  { code: '+968', name: 'Oman', flag: '🇴🇲', iso: 'OM' },
  { code: '+92', name: 'Pakistan', flag: '🇵🇰', iso: 'PK' },
  { code: '+507', name: 'Panama', flag: '🇵🇦', iso: 'PA' },
  { code: '+51', name: 'Peru', flag: '🇵🇪', iso: 'PE' },
  { code: '+63', name: 'Philippines', flag: '🇵🇭', iso: 'PH' },
  { code: '+974', name: 'Qatar', flag: '🇶🇦', iso: 'QA' },
  { code: '+381', name: 'Serbia', flag: '🇷🇸', iso: 'RS' },
  { code: '+421', name: 'Slovakia', flag: '🇸🇰', iso: 'SK' },
  { code: '+386', name: 'Slovenia', flag: '🇸🇮', iso: 'SI' },
  { code: '+94', name: 'Sri Lanka', flag: '🇱🇰', iso: 'LK' },
  { code: '+886', name: 'Taiwan', flag: '🇹🇼', iso: 'TW' },
  { code: '+66', name: 'Thailand', flag: '🇹🇭', iso: 'TH' },
  { code: '+216', name: 'Tunisia', flag: '🇹🇳', iso: 'TN' },
  { code: '+598', name: 'Uruguay', flag: '🇺🇾', iso: 'UY' },
  { code: '+998', name: 'Uzbekistan', flag: '🇺🇿', iso: 'UZ' },
  { code: '+84', name: 'Vietnam', flag: '🇻🇳', iso: 'VN' }
];
