export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS';

export interface HeaderKeyValue {
  key: string;
  value: string;
  enabled?: boolean;
  description?: string;
}

export interface QueryParam {
  key: string;
  value: string;
  enabled?: boolean;
}

export interface PostmanRequestPayload {
  mode?: 'raw' | 'urlencoded' | 'formdata';
  raw?: string;
  urlencoded?: HeaderKeyValue[];
  formdata?: HeaderKeyValue[];
}

export interface PostmanUrl {
  raw?: string;
  protocol?: string;
  host?: string[];
  path?: string[];
  query?: QueryParam[];
}

export interface PostmanRequest {
  method: HttpMethod;
  header?: HeaderKeyValue[];
  body?: PostmanRequestPayload;
  url: PostmanUrl | string;
  description?: string;
}

export interface PostmanItem {
  id?: string;
  name: string;
  description?: string;
  request?: PostmanRequest;
  item?: PostmanItem[]; // Recursive nested items / subfolders
}

export interface PostmanCollection {
  info: {
    _postman_id?: string;
    name: string;
    description?: string;
    schema: string;
  };
  item: PostmanItem[];
  variable?: HeaderKeyValue[];
}

export interface PostmanEnvironmentVariable {
  key: string;
  value: string;
  enabled?: boolean;
  type?: string;
}

export interface PostmanEnvironment {
  id?: string;
  name: string;
  values: PostmanEnvironmentVariable[];
}

// Tree view Node representation
export interface TreeNode {
  id: string;
  name: string;
  type: 'folder' | 'endpoint';
  method?: HttpMethod;
  url?: string;
  description?: string;
  request?: PostmanRequest;
  children?: TreeNode[];
  parentId?: string | null;
  path: string; // Breadcrumb path like "Auth / Login"
}

// Assertion & Test definition generated by AI
export type AssertionType = 
  | 'status_code' 
  | 'latency_sla' 
  | 'header_exists' 
  | 'json_schema' 
  | 'body_contains' 
  | 'value_match'
  | 'extract_variable';

export interface TestCaseRule {
  id: string;
  type: AssertionType;
  description: string;
  expectedValue?: string | number | boolean;
  jsonPath?: string; // e.g. "data.token" or "users[0].id"
  targetVariableKey?: string; // e.g. "authToken" for extracted vars
}

export interface EndpointTestSuite {
  endpointId: string;
  endpointName: string;
  method: HttpMethod;
  url: string;
  generatedBy: 'gemini_ai' | 'smart_heuristic';
  summary: string;
  testCases: TestCaseRule[];
}

// Execution status
export type ExecutionStatus = 'pending' | 'running' | 'passed' | 'failed' | 'skipped';

export interface AssertionResult {
  id: string;
  description: string;
  status: 'pass' | 'fail';
  expected?: string | number | boolean;
  actual?: string | number | boolean;
  message?: string;
}

export interface EndpointExecutionResult {
  endpointId: string;
  name: string;
  method: HttpMethod;
  url: string;
  resolvedUrl: string;
  status: ExecutionStatus;
  statusCode?: number;
  statusText?: string;
  responseTimeMs: number;
  requestHeaders: Record<string, string>;
  requestBody?: string;
  responseHeaders: Record<string, string>;
  responseBody?: string;
  responseSizeByte?: number;
  assertionResults: AssertionResult[];
  extractedVariables?: Record<string, string>;
  error?: string;
  executedAt: string;
}

export interface RunSummary {
  total: number;
  passed: number;
  failed: number;
  running: number;
  pending: number;
  avgLatencyMs: number;
  minLatencyMs: number;
  maxLatencyMs: number;
  startTime?: string;
  endTime?: string;
  status: 'idle' | 'running' | 'paused' | 'completed';
}
